<?php

declare(strict_types=1);

namespace MMAE\Phones\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use MMAE\Phones\CountryDetector;

/**
 * Compiles the current `config/phones.php` into a ready-to-load lookup file.
 *
 * {@see CountryDetector} matches an international number by dialing code. Rather
 * than rebuild that index from the schema on every request, this command bakes
 * it into `config/phone-lookup.php` via {@see CountryDetector::compileIndex()}:
 * an array keyed by dialing code, each entry a [regex, countries] pair where
 * countries sharing an identical pattern are grouped so it is tested once. The
 * detector loads that file directly (no runtime compile).
 *
 * The package ships a lookup file built from its bundled schema. Re-run this
 * after publishing and extending `config/phones.php` so detection sees the new
 * codes; without a regenerate the detector falls back to compiling at runtime.
 */
class BuildLookupCommand extends Command
{
    protected $signature = 'phones:build-lookup {--path= : Absolute path to write the lookup file to}';

    protected $description = 'Compile config/phones.php into the config/phone-lookup.php detection index';

    public function handle(): int
    {
        /** @var array<string, array<string, string>> $countries */
        $countries = config('phones', []);

        $byLength = CountryDetector::compileByLength($countries);

        if ($byLength === []) {
            $this->components->error('No usable country schemas found in config("phones"). Nothing to compile.');

            return self::FAILURE;
        }

        $path = $this->resolvePath();
        File::ensureDirectoryExists(dirname($path));
        File::put($path, $this->render($byLength));

        $this->components->info(sprintf(
            'Compiled a length-first index (%d length buckets) to %s',
            count($byLength), $path,
        ));

        return self::SUCCESS;
    }

    /**
     * Absolute destination path for the lookup file.
     */
    protected function resolvePath(): string
    {
        $path = $this->option('path');

        if (is_string($path) && $path !== '') {
            return $path;
        }

        return config_path('phone-lookup.php');
    }

    /**
     * Build the `config/phone-lookup.php` contents: the ready-to-walk length-first
     * index, exported as a constant literal so {@see CountryDetector} loads it with
     * no runtime transform.
     *
     * @param  array<int, mixed>  $byLength
     */
    protected function render(array $byLength): string
    {
        // indent 1 so the body nests correctly under `'byLength' =>` below
        $export = $this->export($byLength, 1);

        return <<<PHP
        <?php

        /**
         * Precompiled phone-number detection index for mmae/phones.
         *
         * Generated by `php artisan phones:build-lookup` from config("phones").
         * Loaded verbatim by MMAE\\Phones\\CountryDetector::detect() — no runtime
         * build. Re-run after editing config/phones.php — do not edit by hand.
         *
         * Shape: 'byLength' keyed by total (dialing code + subscriber) length; each
         * value is a dialing-code trie of the same-length countries, whose leaf node
         * carries '\$' => [[anchored subscriber regex, [[config ordinal, ISO code],
         * ...]], ...]. detect() jumps to the input's length bucket, then walks the
         * dialing code and tests the regex — the length needs no separate gate.
         */

        return [
            'byLength' => {$export},
        ];

        PHP;
    }

    /**
     * Export a value as short-array (`[...]`) PHP source, so a regenerated lookup
     * file stays Pint-clean (var_export only emits the long `array(...)` form).
     * Sequential-integer-keyed arrays render as bare lists; everything else keeps
     * its keys. Indentation is four spaces per level from $indent.
     */
    protected function export(mixed $value, int $indent): string
    {
        if (! is_array($value)) {
            return var_export($value, true);
        }

        if ($value === []) {
            return '[]';
        }

        $pad = str_repeat('    ', $indent + 1);
        $isList = array_is_list($value);

        $lines = [];
        foreach ($value as $key => $item) {
            $prefix = $isList ? '' : (is_int($key) ? $key : var_export($key, true)).' => ';
            $lines[] = $pad.$prefix.$this->export($item, $indent + 1).',';
        }

        return "[\n".implode("\n", $lines)."\n".str_repeat('    ', $indent).']';
    }
}
