<?php

declare(strict_types=1);

namespace MMAE\Phones\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use MMAE\Phones\CountryDetector;
use MMAE\Phones\Support\LookupCompiler;

/**
 * Bakes `config/phones.php` into the `config/phone-lookup.php` detection index
 * via {@see LookupCompiler::compile()}, which {@see CountryDetector} loads directly.
 *
 * Run `php artisan phones:build-lookup` after publishing and extending
 * `config/phones.php` so detection sees the new codes; detection has no runtime
 * fallback and throws if the index is missing.
 */
class BuildLookupCommand extends Command
{
    protected $signature = 'phones:build-lookup {--path= : Absolute path to write the lookup file to}';

    protected $description = 'Compile config/phones.php into the config/phone-lookup.php detection index';

    public function handle(): int
    {
        /** @var array<string, array<string, string>> $countries */
        $countries = config('phones', []);

        $index = LookupCompiler::compile($countries);

        if ($index === []) {
            $this->components->error('No usable country schemas found in config("phones"). Nothing to compile.');

            return self::FAILURE;
        }

        $path = $this->resolvePath();
        File::ensureDirectoryExists(dirname($path));
        File::put($path, $this->render($index));

        $this->components->info(sprintf(
            'Compiled a length-first index (%d length buckets) to %s',
            count($index), $path,
        ));

        return self::SUCCESS;
    }

    /**
     * Absolute destination path for the lookup file.
     */
    protected function resolvePath(): string
    {
        $path = $this->option('path');

        if (is_string($path) && $path !== '') {
            return $path;
        }

        return config_path('phone-lookup.php');
    }

    /**
     * Build the `config/phone-lookup.php` contents: the length-first index as a
     * plain `return` literal via `var_export`. The generated file is excluded
     * from Pint, so its unformatted `array(...)` output is fine.
     *
     * @param  array<int, mixed>  $index
     */
    protected function render(array $index): string
    {
        $export = var_export(['index' => $index], true);

        return <<<PHP
        <?php

        /**
         * Precompiled phone-number detection index for mmae/phones.
         *
         * Generated by `php artisan phones:build-lookup` from config("phones").
         * Loaded verbatim by MMAE\\Phones\\CountryDetector::detect() — no runtime
         * build and no fallback. Re-run after editing config/phones.php; do NOT
         * edit by hand (generated artifact, excluded from Pint).
         *
         * Shape: 'index' keyed by total (dialing code + subscriber) length; each
         * value is a dialing-code trie whose leaf carries '\$' => [[anchored
         * subscriber regex, [[config ordinal, ISO code], ...]], ...] and/or '#' =>
         * width => provider => [[ordinal, code], ...] (a fixed-width literal-prefix
         * map). detect() jumps to the input's length bucket, then walks the code.
         */

        return {$export};

        PHP;
    }
}
