<?php

declare(strict_types=1);

namespace MMAE\Phones\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use MMAE\Phones\Base\BasePhone;
use MMAE\Phones\Phone;
use MMAE\Phones\Placeholders\Placeholder;
use MMAE\Phones\Rules\PhoneRule;

/**
 * Regenerates the PhpStorm metadata for the current `config/phones.php`.
 *
 * The metadata shipped inside the package is frozen at the published country
 * list; once an app publishes and extends `config/phones.php`, run this command
 * to write an app-local `.phpstorm.meta.php/phones.php` that registers every
 * currently configured country code for the `$countryCode` autocomplete of
 * {@see Phone::make()}, {@see PhoneRule::make()},
 * {@see Placeholder::make()}, and {@see BasePhone::for()}.
 *
 * The file lives in a `.phpstorm.meta.php/` directory, which PhpStorm merges,
 * so it never clobbers an existing root `.phpstorm.meta.php`.
 */
class GenerateIdeHelperCommand extends Command
{
    protected $signature = 'phones:ide-helper {--path= : Absolute path to write the metadata file to}';

    protected $description = 'Generate PhpStorm autocomplete metadata for the configured phone country codes';

    public function handle(): int
    {
        /** @var array<string, mixed> $config */
        $config = config('phones', []);

        $codes = array_values(array_filter(
            array_map(strval(...), array_keys($config)),
            static fn (string $code): bool => $code !== '',
        ));
        sort($codes);

        if ($codes === []) {
            $this->components->error('No country codes found in config("phones"). Nothing to generate.');

            return self::FAILURE;
        }

        $path = $this->resolvePath();
        File::ensureDirectoryExists(dirname($path));
        File::put($path, $this->render($codes));

        $this->components->info(sprintf('Wrote %d country codes to %s', count($codes), $path));

        return self::SUCCESS;
    }

    /**
     * Absolute destination path for the metadata file.
     */
    protected function resolvePath(): string
    {
        $path = $this->option('path');

        if (is_string($path) && $path !== '') {
            return $path;
        }

        return base_path('.phpstorm.meta.php/phones.php');
    }

    /**
     * Build the `.phpstorm.meta.php` contents for the given codes.
     *
     * @param  list<string>  $codes
     */
    protected function render(array $codes): string
    {
        $list = implode("\n", array_map(
            static fn (string $code): string => "        '{$code}',",
            $codes,
        ));

        return <<<PHP
        <?php

        /**
         * PhpStorm / IDE metadata for mmae/phones — NOT loaded at runtime.
         *
         * Generated by `php artisan phones:ide-helper` from the current
         * config("phones") keys. Re-run after editing config/phones.php.
         */

        namespace PHPSTORM_META {

            registerArgumentsSet(
                'mmae_phones_country_codes',
        {$list}
            );

            expectedArguments(\\MMAE\\Phones\\Phone::make(), 1, argumentsSet('mmae_phones_country_codes'));
            expectedArguments(\\MMAE\\Phones\\Base\\BasePhone::for(), 0, argumentsSet('mmae_phones_country_codes'));
            expectedArguments(\\MMAE\\Phones\\Rules\\PhoneRule::make(), 0, argumentsSet('mmae_phones_country_codes'));
            expectedArguments(\\MMAE\\Phones\\Placeholders\\Placeholder::make(), 0, argumentsSet('mmae_phones_country_codes'));
        }

        PHP;
    }
}
