<?php

/**
 * Precompiled phone-number detection index for mmae/phones.
 *
 * Generated by `php artisan phones:build-lookup` from config("phones").
 * Loaded verbatim by MMAE\Phones\CountryDetector::detect() — no runtime
 * build and no fallback. Re-run after editing config/phones.php; do NOT
 * edit by hand (generated artifact, excluded from Pint).
 *
 * Shape: 'index' keyed by total (dialing code + subscriber) length; each
 * value is a dialing-code trie whose leaf carries '$' => [[anchored
 * subscriber regex, [[config ordinal, ISO code], ...]], ...] and/or '#' =>
 * width => provider => [[ordinal, code], ...] (a fixed-width literal-prefix
 * map). detect() jumps to the input's length bucket, then walks the code.
 */

return array (
  'index' => 
  array (
    12 => 
    array (
      2 => 
      array (
        1 => 
        array (
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[1-5])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 0,
                    1 => 'LY',
                  ),
                ),
              ),
            ),
          ),
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[5-7][0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 69,
                    1 => 'DZ',
                  ),
                ),
              ),
            ),
          ),
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[6-7][0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 70,
                    1 => 'MA',
                  ),
                ),
              ),
            ),
          ),
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 183,
                    1 => 'SS',
                  ),
                ),
              ),
            ),
          ),
        ),
        0 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>1[0125])(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 1,
                  1 => 'EG',
                ),
              ),
            ),
          ),
        ),
        5 => 
        array (
          4 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[17]\\d)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 67,
                    1 => 'KE',
                  ),
                ),
              ),
            ),
          ),
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[789]\\d)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 73,
                    1 => 'ET',
                  ),
                ),
              ),
            ),
          ),
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[2389])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 168,
                    1 => 'RW',
                  ),
                ),
              ),
            ),
          ),
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 170,
                    1 => 'UG',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[67]\\d)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 171,
                    1 => 'TZ',
                  ),
                ),
              ),
            ),
          ),
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>8[2-7])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 173,
                    1 => 'MZ',
                  ),
                ),
              ),
            ),
          ),
        ),
        3 => 
        array (
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[2-5][0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 68,
                    1 => 'GH',
                  ),
                ),
              ),
            ),
          ),
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6[0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 74,
                    1 => 'CM',
                  ),
                ),
              ),
            ),
          ),
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[4-8]\\d)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 157,
                    1 => 'LR',
                  ),
                ),
              ),
            ),
          ),
        ),
        6 => 
        array (
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[1-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 72,
                    1 => 'ZW',
                  ),
                ),
              ),
            ),
          ),
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[5-7])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 76,
                    1 => 'ZM',
                  ),
                ),
              ),
            ),
          ),
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>3[2-4])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 172,
                    1 => 'MG',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[89]\\d)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 174,
                    1 => 'MW',
                  ),
                ),
              ),
            ),
          ),
          4 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>8[0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 179,
                    1 => 'NA',
                  ),
                ),
              ),
            ),
          ),
        ),
        4 => 
        array (
          4 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 75,
                    1 => 'AO',
                  ),
                ),
              ),
            ),
          ),
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 110,
                    1 => 'SD',
                  ),
                ),
              ),
            ),
          ),
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>0[1-6])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 162,
                    1 => 'CG',
                  ),
                ),
              ),
            ),
          ),
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[89]\\d)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 163,
                    1 => 'CD',
                  ),
                ),
              ),
            ),
          ),
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>222|55\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 165,
                    1 => 'GQ',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[5-7])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 180,
                    1 => 'GW',
                  ),
                ),
              ),
            ),
          ),
        ),
        2 => 
        array (
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 147,
                    1 => 'SN',
                  ),
                ),
              ),
            ),
          ),
          4 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6[0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 150,
                    1 => 'GN',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      9 => 
      array (
        6 => 
        array (
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>5)(?<digits>\\d{8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 2,
                    1 => 'SA',
                  ),
                ),
              ),
            ),
          ),
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[789])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 9,
                    1 => 'JO',
                  ),
                ),
              ),
            ),
          ),
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>3|7[01]|76|78|79)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 10,
                    1 => 'LB',
                  ),
                ),
              ),
            ),
          ),
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[3-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 11,
                    1 => 'SY',
                  ),
                ),
              ),
            ),
          ),
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 113,
                    1 => 'YE',
                  ),
                ),
              ),
            ),
          ),
        ),
        7 => 
        array (
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>5[024568])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 3,
                    1 => 'AE',
                  ),
                ),
              ),
            ),
          ),
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>5[6-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 105,
                    1 => 'PS',
                  ),
                ),
              ),
            ),
          ),
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>5[0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 114,
                    1 => 'IL',
                  ),
                ),
              ),
            ),
          ),
        ),
        0 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>5\\d)(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 40,
                  1 => 'TR',
                ),
              ),
            ),
          ),
        ),
        1 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>[6-9])(?<digits>\\d{9})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 43,
                  1 => 'IN',
                ),
              ),
            ),
          ),
        ),
        2 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>3[0-9])(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 44,
                  1 => 'PK',
                ),
              ),
            ),
          ),
        ),
        9 => 
        array (
          4 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[4-6][0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 81,
                    1 => 'AZ',
                  ),
                ),
              ),
            ),
          ),
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 107,
                    1 => 'UZ',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>5[0-9]{2})(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 115,
                    1 => 'GE',
                  ),
                ),
              ),
            ),
          ),
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[57][0-9]{2})(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 117,
                    1 => 'KG',
                  ),
                ),
              ),
            ),
          ),
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[49]\\d)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 118,
                    1 => 'TJ',
                  ),
                ),
              ),
            ),
          ),
        ),
        8 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>9[0-9])(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 100,
                  1 => 'IR',
                ),
              ),
            ),
          ),
        ),
      ),
      3 => 
      array (
        5 => 
        array (
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>4\\d|5\\d|6\\d|45|50|46|40|41|42|44|45|46|50|51|52|53|54|55|56|58|59)(?<digits>\\d{7,8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 15,
                    1 => 'FI',
                  ),
                ),
              ),
            ),
          ),
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>8[3-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 21,
                    1 => 'IE',
                  ),
                ),
              ),
            ),
          ),
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6\\d)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 25,
                    1 => 'LU',
                  ),
                ),
              ),
            ),
          ),
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9\\d)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 32,
                    1 => 'PT',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6[6-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 77,
                    1 => 'AL',
                  ),
                ),
              ),
            ),
          ),
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[489]\\d)(?<digits>\\d{5,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 84,
                    1 => 'BG',
                  ),
                ),
              ),
            ),
          ),
        ),
        0 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>6[69])(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 18,
                  1 => 'GR',
                ),
              ),
            ),
          ),
        ),
        9 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>3\\d)(?<digits>\\d{8,9})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 22,
                  1 => 'IT',
                ),
              ),
            ),
          ),
        ),
        7 => 
        array (
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6\\d)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 27,
                    1 => 'MC',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[2-4][0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 82,
                    1 => 'BY',
                  ),
                ),
              ),
            ),
          ),
        ),
        8 => 
        array (
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6\\d)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 34,
                    1 => 'RS',
                  ),
                ),
              ),
            ),
          ),
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>3[01]|4[01]|51|64|68|70|71|73|77|78)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 36,
                    1 => 'SI',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[1-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 85,
                    1 => 'HR',
                  ),
                ),
              ),
            ),
          ),
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[5-9][0-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 112,
                    1 => 'UA',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      4 => 
      array (
        9 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>1[5-7])(?<digits>\\d{8,9})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 17,
                  1 => 'DE',
                ),
              ),
            ),
          ),
        ),
        2 => 
        array (
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9\\d)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 35,
                    1 => 'SK',
                  ),
                ),
              ),
            ),
          ),
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[67]\\d)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 87,
                    1 => 'CZ',
                  ),
                ),
              ),
            ),
          ),
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[67]\\d)(?<digits>\\d{5,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 123,
                    1 => 'LI',
                  ),
                ),
              ),
            ),
          ),
        ),
        6 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>7[0236-9])(?<digits>\\d{7,8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 38,
                  1 => 'SE',
                ),
              ),
            ),
          ),
        ),
        4 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>7\\d{3})(?<digits>\\d{6})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 41,
                  1 => 'GB',
                ),
              ),
            ),
          ),
        ),
        3 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>6[4-9])(?<digits>\\d{5,11})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 80,
                  1 => 'AT',
                ),
              ),
            ),
          ),
        ),
      ),
      6 => 
      array (
        0 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>1[0-9])(?<digits>\\d{7,8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 48,
                  1 => 'MY',
                ),
              ),
            ),
          ),
        ),
        2 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>8[1-9])(?<digits>\\d{7,10})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 50,
                  1 => 'ID',
                ),
              ),
            ),
          ),
        ),
        3 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>9[0-9])(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 51,
                  1 => 'PH',
                ),
              ),
            ),
          ),
        ),
        4 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>2[0-9])(?<digits>\\d{7,8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 56,
                  1 => 'NZ',
                ),
              ),
            ),
          ),
        ),
      ),
      8 => 
      array (
        1 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>[789]0)(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 53,
                  1 => 'JP',
                ),
              ),
            ),
          ),
        ),
        2 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>1[0-9])(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 54,
                  1 => 'KR',
                ),
              ),
            ),
          ),
        ),
        5 => 
        array (
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[1-9]\\d)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 130,
                    1 => 'KH',
                  ),
                ),
              ),
            ),
          ),
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>20)(?<digits>\\d{7,8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 131,
                    1 => 'LA',
                  ),
                ),
              ),
            ),
          ),
        ),
        8 => 
        array (
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9\\d)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 134,
                    1 => 'TW',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      5 => 
      array (
        2 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>[2-9]\\d)(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 58,
                  1 => 'MX',
                ),
              ),
            ),
          ),
        ),
        5 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>[1-9][1-9])(?<digits>\\d{8,9})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 59,
                  1 => 'BR',
                ),
              ),
            ),
          ),
        ),
        4 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>9)(?<digits>\\d{8,10})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 60,
                  1 => 'AR',
                ),
              ),
            ),
          ),
        ),
        7 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>3[0-9])(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 62,
                  1 => 'CO',
                ),
              ),
            ),
          ),
        ),
        8 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>4[0-9])(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 64,
                  1 => 'VE',
                ),
              ),
            ),
          ),
        ),
        9 => 
        array (
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9)(?<digits>\\d{8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 98,
                    1 => 'EC',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[6-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 106,
                    1 => 'PY',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
    11 => 
    array (
      9 => 
      array (
        6 => 
        array (
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[6|9|5])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 4,
                    1 => 'KW',
                  ),
                ),
              ),
            ),
          ),
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[7|9]\\d{1})(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 7,
                    1 => 'OM',
                  ),
                ),
              ),
            ),
          ),
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>3|7[01]|76|78|79)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 10,
                    1 => 'LB',
                  ),
                ),
              ),
            ),
          ),
        ),
        7 => 
        array (
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>3[2-9])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 5,
                    1 => 'BH',
                  ),
                ),
              ),
            ),
          ),
          4 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[5|6|3|7]\\d{1})(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 6,
                    1 => 'QA',
                  ),
                ),
              ),
            ),
          ),
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[8-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 103,
                    1 => 'MN',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>17)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 128,
                    1 => 'BT',
                  ),
                ),
              ),
            ),
          ),
        ),
        3 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>7[0-9])(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 8,
                  1 => 'AF',
                ),
              ),
            ),
          ),
        ),
        4 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>7[01245678])(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 46,
                  1 => 'LK',
                ),
              ),
            ),
          ),
        ),
        9 => 
        array (
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6[0-9])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 119,
                    1 => 'TM',
                  ),
                ),
              ),
            ),
          ),
        ),
        5 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>9\\d)(?<digits>\\d{6,7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 129,
                  1 => 'MM',
                ),
              ),
            ),
          ),
        ),
      ),
      1 => 
      array (
        '$' => 
        array (
          0 => 
          array (
            0 => '/^(?<provider>\\d{3})(?<digits>\\d{7})$/',
            1 => 
            array (
              0 => 
              array (
                0 => 13,
                1 => 'US',
              ),
              1 => 
              array (
                0 => 57,
                1 => 'CA',
              ),
            ),
          ),
          1 => 
          array (
            0 => '/^(?<provider>8[0-4][0-9])(?<digits>\\d{7})$/',
            1 => 
            array (
              0 => 
              array (
                0 => 91,
                1 => 'DO',
              ),
            ),
          ),
        ),
        '#' => 
        array (
          3 => 
          array (
            787 => 
            array (
              0 => 
              array (
                0 => 142,
                1 => 'PR',
              ),
            ),
            939 => 
            array (
              0 => 
              array (
                0 => 142,
                1 => 'PR',
              ),
            ),
            876 => 
            array (
              0 => 
              array (
                0 => 143,
                1 => 'JM',
              ),
            ),
            658 => 
            array (
              0 => 
              array (
                0 => 143,
                1 => 'JM',
              ),
            ),
            868 => 
            array (
              0 => 
              array (
                0 => 144,
                1 => 'TT',
              ),
            ),
            246 => 
            array (
              0 => 
              array (
                0 => 145,
                1 => 'BB',
              ),
            ),
            242 => 
            array (
              0 => 
              array (
                0 => 146,
                1 => 'BS',
              ),
            ),
            264 => 
            array (
              0 => 
              array (
                0 => 192,
                1 => 'AI',
              ),
            ),
            268 => 
            array (
              0 => 
              array (
                0 => 193,
                1 => 'AG',
              ),
            ),
            345 => 
            array (
              0 => 
              array (
                0 => 194,
                1 => 'KY',
              ),
            ),
            767 => 
            array (
              0 => 
              array (
                0 => 195,
                1 => 'DM',
              ),
            ),
            473 => 
            array (
              0 => 
              array (
                0 => 196,
                1 => 'GD',
              ),
            ),
            664 => 
            array (
              0 => 
              array (
                0 => 197,
                1 => 'MS',
              ),
            ),
            869 => 
            array (
              0 => 
              array (
                0 => 198,
                1 => 'KN',
              ),
            ),
            758 => 
            array (
              0 => 
              array (
                0 => 199,
                1 => 'LC',
              ),
            ),
            784 => 
            array (
              0 => 
              array (
                0 => 200,
                1 => 'VC',
              ),
            ),
            649 => 
            array (
              0 => 
              array (
                0 => 201,
                1 => 'TC',
              ),
            ),
            284 => 
            array (
              0 => 
              array (
                0 => 202,
                1 => 'VG',
              ),
            ),
            340 => 
            array (
              0 => 
              array (
                0 => 203,
                1 => 'VI',
              ),
            ),
            684 => 
            array (
              0 => 
              array (
                0 => 204,
                1 => 'AS',
              ),
            ),
            671 => 
            array (
              0 => 
              array (
                0 => 205,
                1 => 'GU',
              ),
            ),
            670 => 
            array (
              0 => 
              array (
                0 => 206,
                1 => 'MP',
              ),
            ),
            441 => 
            array (
              0 => 
              array (
                0 => 207,
                1 => 'BM',
              ),
            ),
            721 => 
            array (
              0 => 
              array (
                0 => 208,
                1 => 'SX',
              ),
            ),
          ),
        ),
      ),
      3 => 
      array (
        3 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>6|7)(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 16,
                  1 => 'FR',
                ),
              ),
            ),
          ),
        ),
        6 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>20|30|70)(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 19,
                  1 => 'HU',
                ),
              ),
            ),
          ),
        ),
        7 => 
        array (
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>2\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 23,
                    1 => 'LV',
                  ),
                ),
              ),
            ),
          ),
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 24,
                    1 => 'LT',
                  ),
                ),
              ),
            ),
          ),
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6\\d)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 27,
                    1 => 'MC',
                  ),
                ),
              ),
            ),
          ),
          4 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[4-9][0-9])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 79,
                    1 => 'AM',
                  ),
                ),
              ),
            ),
          ),
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[5-8])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 88,
                    1 => 'EE',
                  ),
                ),
              ),
            ),
          ),
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[6-7])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 102,
                    1 => 'MD',
                  ),
                ),
              ),
            ),
          ),
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6[0-9])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 124,
                    1 => 'SM',
                  ),
                ),
              ),
            ),
          ),
        ),
        5 => 
        array (
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6\\d)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 25,
                    1 => 'LU',
                  ),
                ),
              ),
            ),
          ),
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[79]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 26,
                    1 => 'MT',
                  ),
                ),
              ),
            ),
          ),
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[489]\\d)(?<digits>\\d{5,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 84,
                    1 => 'BG',
                  ),
                ),
              ),
            ),
          ),
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[0-9])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 86,
                    1 => 'CY',
                  ),
                ),
              ),
            ),
          ),
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>5[6-8])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 125,
                    1 => 'GI',
                  ),
                ),
              ),
            ),
          ),
        ),
        8 => 
        array (
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 28,
                    1 => 'ME',
                  ),
                ),
              ),
            ),
          ),
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>3[01]|4[01]|51|64|68|70|71|73|77|78)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 36,
                    1 => 'SI',
                  ),
                ),
              ),
            ),
          ),
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6[0-6])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 120,
                    1 => 'BA',
                  ),
                ),
              ),
            ),
          ),
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[0-9])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 121,
                    1 => 'MK',
                  ),
                ),
              ),
            ),
          ),
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>4[3-9])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 122,
                    1 => 'XK',
                  ),
                ),
              ),
            ),
          ),
        ),
        1 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>6)(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 29,
                  1 => 'NL',
                ),
              ),
            ),
          ),
        ),
        4 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>6\\d|7[1-9])(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 37,
                  1 => 'ES',
                ),
              ),
            ),
          ),
        ),
        2 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>4[5-9])(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 83,
                  1 => 'BE',
                ),
              ),
            ),
          ),
        ),
      ),
      4 => 
      array (
        8 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>5\\d|6\\d|7\\d|8\\d)(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 31,
                  1 => 'PL',
                ),
              ),
            ),
          ),
        ),
        0 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>[67]\\d)(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 33,
                  1 => 'RO',
                ),
              ),
            ),
          ),
        ),
        6 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>7[0236-9])(?<digits>\\d{7,8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 38,
                  1 => 'SE',
                ),
              ),
            ),
          ),
        ),
        1 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>7[5-9])(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 39,
                  1 => 'CH',
                ),
              ),
            ),
          ),
        ),
        3 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>6[4-9])(?<digits>\\d{5,11})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 80,
                  1 => 'AT',
                ),
              ),
            ),
          ),
        ),
        2 => 
        array (
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[67]\\d)(?<digits>\\d{5,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 123,
                    1 => 'LI',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      8 => 
      array (
        4 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>3[2-9]|5[2689]|7[0|6-9]|8[1-9]|9[0-9])(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 42,
                  1 => 'VN',
                ),
              ),
            ),
          ),
        ),
        5 => 
        array (
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[5-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 99,
                    1 => 'HK',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[1-9]\\d)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 130,
                    1 => 'KH',
                  ),
                ),
              ),
            ),
          ),
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 135,
                    1 => 'MO',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      6 => 
      array (
        0 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>1[0-9])(?<digits>\\d{7,8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 48,
                  1 => 'MY',
                ),
              ),
            ),
          ),
        ),
        2 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>8[1-9])(?<digits>\\d{7,10})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 50,
                  1 => 'ID',
                ),
              ),
            ),
          ),
        ),
        1 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>4[0-9])(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 55,
                  1 => 'AU',
                ),
              ),
            ),
          ),
        ),
        4 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>2[0-9])(?<digits>\\d{7,8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 56,
                  1 => 'NZ',
                ),
              ),
            ),
          ),
        ),
        6 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>[6-9])(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 111,
                  1 => 'TH',
                ),
              ),
            ),
          ),
        ),
        7 => 
        array (
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[2-8])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 133,
                    1 => 'TL',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[78]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 185,
                    1 => 'PG',
                  ),
                ),
              ),
            ),
          ),
        ),
        8 => 
        array (
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>8[7-9])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 187,
                    1 => 'PF',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      5 => 
      array (
        4 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>9)(?<digits>\\d{8,10})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 60,
                  1 => 'AR',
                ),
              ),
            ),
          ),
        ),
        6 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>9)(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 61,
                  1 => 'CL',
                ),
              ),
            ),
          ),
        ),
        1 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>9)(?<digits>\\d{8})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 63,
                  1 => 'PE',
                ),
              ),
            ),
          ),
        ),
        0 => 
        array (
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[6-8])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 89,
                    1 => 'CR',
                  ),
                ),
              ),
            ),
          ),
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[6-7])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 92,
                    1 => 'SV',
                  ),
                ),
              ),
            ),
          ),
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[3-5])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 93,
                    1 => 'GT',
                  ),
                ),
              ),
            ),
          ),
          4 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[3-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 94,
                    1 => 'HN',
                  ),
                ),
              ),
            ),
          ),
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 95,
                    1 => 'PA',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[578]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 140,
                    1 => 'NI',
                  ),
                ),
              ),
            ),
          ),
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[34]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 141,
                    1 => 'HT',
                  ),
                ),
              ),
            ),
          ),
        ),
        9 => 
        array (
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9)(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 96,
                    1 => 'UY',
                  ),
                ),
              ),
            ),
          ),
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[67]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 136,
                    1 => 'BO',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      2 => 
      array (
        7 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>[6-8][0-9])(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 65,
                  1 => 'ZA',
                ),
              ),
            ),
          ),
        ),
        1 => 
        array (
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[2-9][0-9])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 71,
                    1 => 'TN',
                  ),
                ),
              ),
            ),
          ),
        ),
        5 => 
        array (
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[7-8])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 97,
                    1 => 'DJ',
                  ),
                ),
              ),
            ),
          ),
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[6-9])(?<digits>\\d{7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 109,
                    1 => 'SO',
                  ),
                ),
              ),
            ),
          ),
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[67]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 169,
                    1 => 'BI',
                  ),
                ),
              ),
            ),
          ),
        ),
        2 => 
        array (
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[234]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 148,
                    1 => 'MR',
                  ),
                ),
              ),
            ),
          ),
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[679]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 149,
                    1 => 'ML',
                  ),
                ),
              ),
            ),
          ),
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[567]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 152,
                    1 => 'BF',
                  ),
                ),
              ),
            ),
          ),
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[89]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 153,
                    1 => 'NE',
                  ),
                ),
              ),
            ),
          ),
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[79]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 154,
                    1 => 'TG',
                  ),
                ),
              ),
            ),
          ),
        ),
        3 => 
        array (
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>5\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 156,
                    1 => 'MU',
                  ),
                ),
              ),
            ),
          ),
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[4-8]\\d)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 157,
                    1 => 'LR',
                  ),
                ),
              ),
            ),
          ),
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[2-9]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 158,
                    1 => 'SL',
                  ),
                ),
              ),
            ),
          ),
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[69]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 160,
                    1 => 'TD',
                  ),
                ),
              ),
            ),
          ),
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[0-7])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 161,
                    1 => 'CF',
                  ),
                ),
              ),
            ),
          ),
        ),
        4 => 
        array (
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>0[2-7])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 164,
                    1 => 'GA',
                  ),
                ),
              ),
            ),
          ),
        ),
        6 => 
        array (
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[56]\\d)(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 175,
                    1 => 'LS',
                  ),
                ),
              ),
            ),
          ),
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[1-8])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 176,
                    1 => 'BW',
                  ),
                ),
              ),
            ),
          ),
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[6-8])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 177,
                    1 => 'SZ',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      7 => 
      array (
        '$' => 
        array (
          0 => 
          array (
            0 => '/^(?<provider>9[0-9])(?<digits>\\d{8})$/',
            1 => 
            array (
              0 => 
              array (
                0 => 108,
                1 => 'RU',
              ),
            ),
          ),
          1 => 
          array (
            0 => '/^(?<provider>7[0-9]{2})(?<digits>\\d{7})$/',
            1 => 
            array (
              0 => 
              array (
                0 => 116,
                1 => 'KZ',
              ),
            ),
          ),
        ),
      ),
    ),
    10 => 
    array (
      9 => 
      array (
        6 => 
        array (
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>3|7[01]|76|78|79)(?<digits>\\d{6,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 10,
                    1 => 'LB',
                  ),
                ),
              ),
            ),
          ),
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[7-9])(?<digits>\\d{6})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 101,
                    1 => 'MV',
                  ),
                ),
              ),
            ),
          ),
        ),
        5 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>9\\d)(?<digits>\\d{6,7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 129,
                  1 => 'MM',
                ),
              ),
            ),
          ),
        ),
      ),
      4 => 
      array (
        5 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>\\d{2})(?<digits>\\d{6})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 14,
                  1 => 'DK',
                ),
              ),
            ),
          ),
        ),
        7 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>4\\d|9\\d)(?<digits>\\d{6})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 30,
                  1 => 'NO',
                ),
              ),
            ),
          ),
        ),
        3 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>6[4-9])(?<digits>\\d{5,11})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 80,
                  1 => 'AT',
                ),
              ),
            ),
          ),
        ),
        2 => 
        array (
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[67]\\d)(?<digits>\\d{5,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 123,
                    1 => 'LI',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      3 => 
      array (
        5 => 
        array (
          4 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[3678]\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 20,
                    1 => 'IS',
                  ),
                ),
              ),
            ),
          ),
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[489]\\d)(?<digits>\\d{5,7})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 84,
                    1 => 'BG',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      6 => 
      array (
        5 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>[89])(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 49,
                  1 => 'SG',
                ),
              ),
            ),
          ),
        ),
        7 => 
        array (
          3 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[78]\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 132,
                    1 => 'BN',
                  ),
                ),
              ),
            ),
          ),
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[789]\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 184,
                    1 => 'FJ',
                  ),
                ),
              ),
            ),
          ),
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[78]\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 189,
                    1 => 'TO',
                  ),
                ),
              ),
            ),
          ),
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[57]\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 190,
                    1 => 'VU',
                  ),
                ),
              ),
            ),
          ),
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[78]\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 191,
                    1 => 'SB',
                  ),
                ),
              ),
            ),
          ),
        ),
        8 => 
        array (
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[2-8])(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 188,
                    1 => 'WS',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      5 => 
      array (
        3 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>5)(?<digits>\\d{7})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 90,
                  1 => 'CU',
                ),
              ),
            ),
          ),
        ),
        9 => 
        array (
          2 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 137,
                    1 => 'GY',
                  ),
                ),
              ),
            ),
          ),
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[678]\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 138,
                    1 => 'SR',
                  ),
                ),
              ),
            ),
          ),
        ),
        0 => 
        array (
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>6\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 139,
                    1 => 'BZ',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      2 => 
      array (
        2 => 
        array (
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[2-9]\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 159,
                    1 => 'GM',
                  ),
                ),
              ),
            ),
          ),
        ),
        3 => 
        array (
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 166,
                    1 => 'ST',
                  ),
                ),
              ),
            ),
          ),
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[59]\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 181,
                    1 => 'CV',
                  ),
                ),
              ),
            ),
          ),
        ),
        9 => 
        array (
          1 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7\\d)(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 167,
                    1 => 'ER',
                  ),
                ),
              ),
            ),
          ),
        ),
        6 => 
        array (
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>3[234])(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 178,
                    1 => 'KM',
                  ),
                ),
              ),
            ),
          ),
        ),
        4 => 
        array (
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>2[5-8])(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 182,
                    1 => 'SC',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
    13 => 
    array (
      9 => 
      array (
        6 => 
        array (
          4 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>7[3-9])(?<digits>\\d{8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 12,
                    1 => 'IQ',
                  ),
                ),
              ),
            ),
          ),
        ),
        7 => 
        array (
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>9[6-8])(?<digits>\\d{8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 47,
                    1 => 'NP',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      3 => 
      array (
        5 => 
        array (
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>4\\d|5\\d|6\\d|45|50|46|40|41|42|44|45|46|50|51|52|53|54|55|56|58|59)(?<digits>\\d{7,8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 15,
                    1 => 'FI',
                  ),
                ),
              ),
            ),
          ),
        ),
        9 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>3\\d)(?<digits>\\d{8,9})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 22,
                  1 => 'IT',
                ),
              ),
            ),
          ),
        ),
      ),
      4 => 
      array (
        9 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>1[5-7])(?<digits>\\d{8,9})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 17,
                  1 => 'DE',
                ),
              ),
            ),
          ),
        ),
        3 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>6[4-9])(?<digits>\\d{5,11})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 80,
                  1 => 'AT',
                ),
              ),
            ),
          ),
        ),
      ),
      8 => 
      array (
        8 => 
        array (
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>1[3-9])(?<digits>\\d{8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 45,
                    1 => 'BD',
                  ),
                ),
              ),
            ),
          ),
        ),
        6 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>1[3-9])(?<digits>\\d{9})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 52,
                  1 => 'CN',
                ),
              ),
            ),
          ),
        ),
        5 => 
        array (
          0 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>19)(?<digits>\\d{8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 104,
                    1 => 'KP',
                  ),
                ),
              ),
            ),
          ),
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>20)(?<digits>\\d{7,8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 131,
                    1 => 'LA',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      6 => 
      array (
        2 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>8[1-9])(?<digits>\\d{7,10})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 50,
                  1 => 'ID',
                ),
              ),
            ),
          ),
        ),
      ),
      5 => 
      array (
        5 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>[1-9][1-9])(?<digits>\\d{8,9})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 59,
                  1 => 'BR',
                ),
              ),
            ),
          ),
        ),
        4 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>9)(?<digits>\\d{8,10})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 60,
                  1 => 'AR',
                ),
              ),
            ),
          ),
        ),
      ),
      2 => 
      array (
        3 => 
        array (
          4 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[7-9][0-9])(?<digits>\\d{8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 66,
                    1 => 'NG',
                  ),
                ),
              ),
            ),
          ),
        ),
        2 => 
        array (
          5 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>0[157])(?<digits>\\d{8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 151,
                    1 => 'CI',
                  ),
                ),
              ),
            ),
          ),
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>01)(?<digits>\\d{8})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 155,
                    1 => 'BJ',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
    14 => 
    array (
      6 => 
      array (
        2 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>8[1-9])(?<digits>\\d{7,10})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 50,
                  1 => 'ID',
                ),
              ),
            ),
          ),
        ),
      ),
      4 => 
      array (
        3 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>6[4-9])(?<digits>\\d{5,11})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 80,
                  1 => 'AT',
                ),
              ),
            ),
          ),
        ),
      ),
    ),
    9 => 
    array (
      3 => 
      array (
        7 => 
        array (
          6 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[3-6])(?<digits>\\d{5})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 78,
                    1 => 'AD',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      4 => 
      array (
        3 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>6[4-9])(?<digits>\\d{5,11})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 80,
                  1 => 'AT',
                ),
              ),
            ),
          ),
        ),
      ),
      2 => 
      array (
        9 => 
        array (
          8 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[257]\\d)(?<digits>\\d{4})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 126,
                    1 => 'FO',
                  ),
                ),
              ),
            ),
          ),
          9 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[245]\\d)(?<digits>\\d{4})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 127,
                    1 => 'GL',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      6 => 
      array (
        8 => 
        array (
          7 => 
          array (
            '$' => 
            array (
              0 => 
              array (
                0 => '/^(?<provider>[789]\\d)(?<digits>\\d{4})$/',
                1 => 
                array (
                  0 => 
                  array (
                    0 => 186,
                    1 => 'NC',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
    15 => 
    array (
      4 => 
      array (
        3 => 
        array (
          '$' => 
          array (
            0 => 
            array (
              0 => '/^(?<provider>6[4-9])(?<digits>\\d{5,11})$/',
              1 => 
              array (
                0 => 
                array (
                  0 => 80,
                  1 => 'AT',
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  ),
);
